config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  resources :things
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/thing.rb
class Thing < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController

  def index

  end

  def new
    @thing = Thing.new
    respond_to do |format|
      format.js
    end
  end

  def create
    @thing = Thing.create(thing_params)

    respond_to do |format|
      if @thing.save
        format.js
      else
        flash[:alert] = "Oops, your thing could not be saved."
        format.js
      end
    end
  end

  def edit
    @thing = Thing.find(params[:id])
    respond_to do |format|
      format.js { }

    end
  end

  def destroy

  end

  def thing_params
    params.require(:thing).permit(:id, :name, :color)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NestedFormsIssue1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6">
        <%= yield %>
      </div>
    </div>
  </div>

  </body>
</html>

app/views/things/_edit.haml
Editing
= @thing.name
%br/

= form_for @thing, remote: true  do  |f|
 = render partial: "things/form", locals: {f: f, thing: @thing}
 = f.submit "Save", class: "btn btn-primary"

app/views/things/_errors.haml
errors!

app/views/things/_form.haml
= f.text_field :name
%label
  Name
%br/

= f.text_field :color
%label
  Color

app/views/things/_line.haml
%td
  = thing.name
%td
  %strong Name
  = thing.name
  %br/
  %strong Color
  = thing.color
  %br/


%td
  = link_to "Edit ", edit_thing_path(thing), remote: true, class: "edit-thing-button btn btn-primary pull-right btn-sm"

app/views/things/_list.haml
%h1
  Your Things

= link_to "New Thing", new_thing_path, 'data-disable-with': "Loading...", remote: true, class: "new-thing-button btn btn-secondary pull-right btn-sm"

.clearfix
.new-thing-form{style: "display: none; position: relative;"}

%table.table.table-striped.things-table
  %thead
    %tr
      %th{:scope => "col"} Name
      %th{:scope => "col"} Color
      %th{:scope => "col"}

  %tbody
    - if things.empty?
      None
    - things.each do |thing|
      %tr{'data-id': thing.id}
        = render partial: "things/line", locals: {thing: thing}

app/views/things/_new.haml
New Thing

= form_with model: @thing,  method: "post" do  |f|
  = render partial: "things/form", locals: {f: f}
  = f.submit "Save", class: "btn btn-primary"

app/views/things/create.js.erb
<% if @thing.errors.none? %>
location.reload()
//$(".new-thing-form").slideUp();
//$(".things-list").html("<%= j render(partial: 'things/list', locals: {things: Thing.all }) %>");


<% else %>
$(".new-thing-form").html("<%= j render(partial: 'things/errors', locals: {resource: @thing}) %>")
$(".new-thing-form").append("<%= j render(partial: 'things/new' ) %><i class='fa fa-times-circle fa-2x' data-name='new-thing' data-role='close-button' />").slideDown();

$(".flash-notices").html("<%= j render 'layouts/flash_notices' %>");
<% end %>

app/views/things/edit.js.erb
$(".things-table tr[data-id=<%= @thing.id %>]").html("<%= j render partial: 'things/edit', locals: {thing: @thing} %>")

app/views/things/index.haml
= render partial: "things/list", locals: {things: Thing.all}

app/views/things/new.js.erb
$(".new-thing-button").fadeOut(function() {
  $(".new-thing-form").html("<%= j render(partial: 'things/new' ) %><i class='fa fa-times-circle fa-2x' data-name='new-thing' data-role='close-button' />").slideDown();
})

app/views/things/update.js.erb
<% if @thing.errors.none? %>
$(".things-table tr[data-id=<%= @thing.id %>]").html("<%= j render partial: 'dashboard/things/line', locals: {thing: @thing} %>")

<% else %>
$(".things-table tr[data-id=<%= @thing.id %>]").html("<%= j render partial: 'dashboard/things/edit', locals: {thing: @thing} %>")
$(".flash-notices").html("<%= j render 'layouts/flash_notices' %>");
<% end %>